### ISSUE TITLE
MongoDB安装指导

### ISSUE THREAD

**Issue by carmel** [ProgrammingTeaching/Python-Web-Crawler#2]
### 安装MongoDB

注意：MongoDB 4.2以后的版本将不再支持Windows 7系统，因此要在Windows 7系统上安装MongoDB需下载4.2及以下版本。
1. 在[官网下载](https://www.mongodb.com/try/download/community)`MongoDB Community Server`的Zip压缩版本。
2. 解压Zip压缩包，将解压后的目录重命名为`mongodb`
3. 在当前目录下打开命令行执行以下命令来创建数据库的数据及日志目录
```bat
md data\db log
```
4. 创建配置文件`mongod.cfg`，内容如下：
```yaml
systemLog:
    destination: file
    # 日志输出目录
    path: "D:\\DB\\mongodb\\log\\mongo.log"
    # 是否以追加方式记录日志
    logAppend: true
    # 是否忽略debug信息
    quiet: true
storage:
    # 数据库目录
    dbPath: "D:\\DB\\mongodb\\data\\db"
    journal:
        # 是否启用日志文件
        enabled: true
net:
    # 绑定ip地址
    bindIp: 0.0.0.0
    # 指定端口号
    port: 27017
setParameter:
    # 是否允许绕过身份验证
    enableLocalhostAuthBypass: false
security:
    # 是否启用安全认证 (enabled / disabled)
    authorization: disabled
```
5. 转到`mongodb\bin`目录执行命令开启MongoDB服务同时设置登录用户名及密码：
```bat
mongod --config "..\mongod.cfg"
mongo
> use admin
> db.createUser(
  {
    user: "Admin",
    pwd: passwordPrompt(), // or cleartext password
    roles: [ { role: "userAdminAnyDatabase", db: "admin" }, "readWriteAnyDatabase" ]
  }
)
```
6. 重启mongod进程并将`security.authorization`改成`enabled`再使用`mongo`命令重新登陆
```bat
mongod --config "..\mongod.cfg"
mongo -u "Admin" -p "admin" --authenticationDatabase "admin"
```
